// Bundles the browser client (src/client/main.ts) and writes it, as a string, to
// generated/client-bundle.ts — which the Worker imports and inlines into the page.
// Also writes generated/last-deployment-timestamp.ts, the build-time stamp (branch +
// build moment) the client imports — emitted here, before esbuild reads main.ts, so
// the bundle always carries the current stamp. See the stamp section below.
//
// Why a build step at all: the client used to be one function serialized with
// clientMain.toString(). Only a function's own body survives that, so the client
// could never import anything, could never be split across files, and had to be
// hand-shimmed against esbuild's own helpers (the __name business in page()). One
// bundle, one <script>, and none of that is true any more.
//
// Why a .ts file holding a string, rather than a .js file imported via wrangler's
// Text rule: a Text glob broad enough to catch the bundle would also catch every
// other .js in the build, and a generated module that simply exports the source is
// both unambiguous and typechecked like anything else.
//
// Why generated/ sits at the repo root and not under src/: the page-edit info-pill is
// the newest mtime under src/. A build artifact rewritten on every dev run would be
// that mtime for ever, and the pill would report the build instead of the last thing
// you wrote. Both the bundle and the deployment stamp this script emits are such
// artifacts, so both live here.
//
// Runs under Node's native type stripping (Node >=22.6) — no build step for the
// build step.
import * as esbuild from "esbuild";
import { execSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const outFile = join(root, "generated", "client-bundle.ts");
const stampFile = join(root, "generated", "last-deployment-timestamp.ts");
const watch = process.argv.includes("--watch");

// ── Deployment stamp ──────────────────────────────────────────────────────────
// The build-time facts the Worker can't read at runtime — the branch being bundled
// and the moment of this build — written as a tiny module the client imports. On a
// deploy this build runs inside `predeploy`, so the stamp is the deploy moment; in
// `dev` it is when you started the dev server. Written before esbuild reads main.ts
// (call site below), so the bundle picks up the current stamp rather than the last.

// A Date → { date: "YYYY-MM-DD", time: "HH:MM:SS" } in US Eastern time
// (America/New_York — shifts EST/EDT with DST) regardless of the build host.
const stampFmt = new Intl.DateTimeFormat("en-CA", {
  timeZone: "America/New_York",
  year: "numeric", month: "2-digit", day: "2-digit",
  hour: "2-digit", minute: "2-digit", second: "2-digit", hourCycle: "h23",
});
function stampParts(d: Date): { date: string; time: string } {
  const o: Record<string, string> = {};
  for (const { type, value } of stampFmt.formatToParts(d)) o[type] = value;
  return { date: `${o.year}-${o.month}-${o.day}`, time: `${o.hour}:${o.minute}:${o.second}` };
}
// Currently checked-out branch (whatever wrangler will bundle). "" if unknown.
function currentBranch(): string {
  try {
    return execSync("git rev-parse --abbrev-ref HEAD", { cwd: root }).toString().trim();
  } catch {
    return "";
  }
}
// The generated stamp references DeploymentStamp — a global from src/shared-types.d.ts,
// in scope wherever tsc compiles this output (client + worker projects).
function writeDeploymentStamp() {
  const stamp = { branch: currentBranch(), deploy: stampParts(new Date()) };
  mkdirSync(dirname(stampFile), { recursive: true });
  writeFileSync(
    stampFile,
    "// Generated by scripts/build-client.mts — do not edit by hand.\n" +
      `export const lastDeploymentTimestamp: DeploymentStamp = ${JSON.stringify(stamp, null, 2)};\n`,
  );
}

// Write the bundled JS out as a TS module exporting it. Lives in a plugin's onEnd so
// that a watch rebuild takes exactly the same path as the one-shot build.
function emit(result: esbuild.BuildResult) {
  if (result.errors.length) return; // esbuild has already printed them
  const js = result.outputFiles![0].text;
  mkdirSync(dirname(outFile), { recursive: true });
  writeFileSync(
    outFile,
    "// Generated by scripts/build-client.mts — do not edit by hand.\n" +
      `export const clientBundle = ${JSON.stringify(js)};\n`,
  );
  console.log(`wrote generated/client-bundle.ts (${(js.length / 1024).toFixed(1)}kb)`);
}

// Stamp first, so the bundle below imports the current values, not the last build's.
writeDeploymentStamp();

// esbuild does not typecheck — that stays tsc's job (npm run typecheck), which sees
// exactly the same files. This step only bundles.
const ctx = await esbuild.context({
  entryPoints: [join(root, "src", "client", "main.ts")],
  bundle: true,
  // IIFE, not ESM: the bundle is inlined into a plain <script> in the page, so it
  // must run on evaluation and must not need module semantics to do it.
  format: "iife",
  target: "es2022",
  platform: "browser",
  write: false, // emit() post-processes into a .ts module instead
  plugins: [{ name: "emit-bundle", setup: (b) => b.onEnd(emit) }],
});

if (watch) {
  await ctx.watch(); // holds the process open; runs alongside wrangler dev
} else {
  await ctx.rebuild();
  await ctx.dispose();
}
