// Bundles the browser client (src/client/main.ts) and writes it, as a string, to
// generated/client-bundle.ts — which the Worker imports and inlines into the page.
//
// Why a build step at all: the client used to be one function serialized with
// clientMain.toString(). Only a function's own body survives that, so the client
// could never import anything, could never be split across files, and had to be
// hand-shimmed against esbuild's own helpers (the __name business in page()). One
// bundle, one <script>, and none of that is true any more.
//
// Why a .ts file holding a string, rather than a .js file imported via wrangler's
// Text rule: a Text glob broad enough to catch the bundle would also catch every
// other .js in the build, and a generated module that simply exports the source is
// both unambiguous and typechecked like anything else.
//
// Why generated/ sits at the repo root and not under src/: the page-edit info-pill is
// the newest mtime under src/ (see generate-deployment-timestamp.mts). A build
// artifact rewritten on every dev run would be that mtime for ever, and the pill
// would report the build instead of the last thing you wrote.
//
// Runs under Node's native type stripping (Node >=22.6) — no build step for the
// build step.
import * as esbuild from "esbuild";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const outFile = join(root, "generated", "client-bundle.ts");
const watch = process.argv.includes("--watch");

// Write the bundled JS out as a TS module exporting it. Lives in a plugin's onEnd so
// that a watch rebuild takes exactly the same path as the one-shot build.
function emit(result: esbuild.BuildResult) {
  if (result.errors.length) return; // esbuild has already printed them
  const js = result.outputFiles![0].text;
  mkdirSync(dirname(outFile), { recursive: true });
  writeFileSync(
    outFile,
    "// Generated by scripts/build-client.mts — do not edit by hand.\n" +
      `export const clientBundle = ${JSON.stringify(js)};\n`,
  );
  console.log(`wrote generated/client-bundle.ts (${(js.length / 1024).toFixed(1)}kb)`);
}

// esbuild does not typecheck — that stays tsc's job (npm run typecheck), which sees
// exactly the same files. This step only bundles.
const ctx = await esbuild.context({
  entryPoints: [join(root, "src", "client", "main.ts")],
  bundle: true,
  // IIFE, not ESM: the bundle is inlined into a plain <script> in the page, so it
  // must run on evaluation and must not need module semantics to do it.
  format: "iife",
  target: "es2022",
  platform: "browser",
  write: false, // emit() post-processes into a .ts module instead
  plugins: [{ name: "emit-bundle", setup: (b) => b.onEnd(emit) }],
});

if (watch) {
  await ctx.watch(); // holds the process open; runs alongside wrangler dev
} else {
  await ctx.rebuild();
  await ctx.dispose();
}
