// Writes src/last-deployment-timestamp.ts with the build-time values the Worker can't
// read at runtime: the branch being deployed and the moment of this deploy. Run by the
// npm pre-deploy hook, so the stamp always reflects the deploy currently in flight.
//
// Runs under Node's native type stripping (Node >=22.6) — no build step, no
// loader: `node scripts/generate-deployment-timestamp.mts` just works.
import { writeFileSync } from "node:fs";
import { execSync } from "node:child_process";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

// The generated file's shape. Declared locally rather than pulled from
// src/shared-types.d.ts: this script is a Node program, outside both the worker
// and the client project. Keep the two in step — if one changes, change the other.
interface StampTime {
  date: string;
  time: string;
}
interface DeploymentStamp {
  branch: string;
  deploy: StampTime;
}

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const outFile = join(root, "src", "last-deployment-timestamp.ts");

// A Date → { date: "YYYY-MM-DD", time: "HH:MM:SS" } in US Eastern time
// (America/New_York — shifts EST/EDT with DST) regardless of the build host.
const fmt = new Intl.DateTimeFormat("en-CA", {
  timeZone: "America/New_York",
  year: "numeric", month: "2-digit", day: "2-digit",
  hour: "2-digit", minute: "2-digit", second: "2-digit", hourCycle: "h23",
});
function parts(d: Date): StampTime {
  const o: Record<string, string> = {};
  for (const { type, value } of fmt.formatToParts(d)) o[type] = value;
  return { date: `${o.year}-${o.month}-${o.day}`, time: `${o.hour}:${o.minute}:${o.second}` };
}

// Currently checked-out branch (whatever wrangler will bundle). "" if unknown.
function currentBranch(): string {
  try {
    return execSync("git rev-parse --abbrev-ref HEAD", { cwd: root }).toString().trim();
  } catch {
    return "";
  }
}

const stamp: DeploymentStamp = {
  branch: currentBranch(),
  deploy: parts(new Date()),
};

const body =
  "// Generated by scripts/generate-deployment-timestamp.mts — do not edit by hand.\n" +
  `export const lastDeploymentTimestamp: DeploymentStamp = ${JSON.stringify(stamp, null, 2)};\n`;
writeFileSync(outFile, body);
console.log("wrote src/last-deployment-timestamp.ts");
