// Writes src/last-deployment-timestamp.ts with build-time values the Worker can't read at
// runtime. Run by the npm pre-deploy / pre-dev hooks:
//   node scripts/generate-deployment-timestamp.mts deploy   → deploy timestamp
//   node scripts/generate-deployment-timestamp.mts dev       → latest src edit + last commit
// The Worker picks which set to show at request time based on hostname.
//
// Runs under Node's native type stripping (Node >=22.6) — no build step, no
// loader: `node scripts/generate-deployment-timestamp.mts` just works.
import { readdirSync, statSync, writeFileSync } from "node:fs";
import { execSync } from "node:child_process";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

// The generated file's shape. Declared locally rather than pulled from
// src/shared-types.d.ts: this script is a Node program, outside both the worker
// and the client project. Keep the two in step — if one changes, change the other.
interface StampTime {
  date: string;
  time: string;
}
interface DeploymentStamp {
  mode: "deploy" | "dev";
  branch: string;
  deploy: StampTime;
  pageEdit: StampTime;
  commit: StampTime;
}

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const outFile = join(root, "src", "last-deployment-timestamp.ts");
const mode: DeploymentStamp["mode"] = process.argv[2] === "deploy" ? "deploy" : "dev";
const empty: StampTime = { date: "", time: "" };

// A Date → { date: "YYYY-MM-DD", time: "HH:MM:SS" } in US Eastern time
// (America/New_York — shifts EST/EDT with DST) regardless of the build host.
const fmt = new Intl.DateTimeFormat("en-CA", {
  timeZone: "America/New_York",
  year: "numeric", month: "2-digit", day: "2-digit",
  hour: "2-digit", minute: "2-digit", second: "2-digit", hourCycle: "h23",
});
function parts(d: Date): StampTime {
  const o: Record<string, string> = {};
  for (const { type, value } of fmt.formatToParts(d)) o[type] = value;
  return { date: `${o.year}-${o.month}-${o.day}`, time: `${o.hour}:${o.minute}:${o.second}` };
}

// Currently checked-out branch (whatever wrangler will bundle). "" if unknown.
function currentBranch(): string {
  try {
    return execSync("git rev-parse --abbrev-ref HEAD", { cwd: root }).toString().trim();
  } catch {
    return "";
  }
}

// Newest mtime under src/, excluding the generated file itself.
function newestSrcMtime(dir: string, acc: number[]): number[] {
  for (const ent of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, ent.name);
    if (ent.isDirectory()) newestSrcMtime(full, acc);
    else if (full !== outFile) acc.push(statSync(full).mtimeMs);
  }
  return acc;
}

const stamp: DeploymentStamp = {
  mode,
  branch: currentBranch(),
  deploy: empty,
  pageEdit: empty,
  commit: empty,
};

// page-edit (newest src mtime) and commit (HEAD time) are computed in BOTH
// modes, so a deploy-written stamp still carries the localhost pills' values.
// The stamp file is single + last-writer-wins, so if only the dev branch filled
// these, a deploy mid-dev-session would blank the localhost pills.
const mtimes = newestSrcMtime(join(root, "src"), []);
if (mtimes.length) stamp.pageEdit = parts(new Date(Math.max(...mtimes)));
try {
  const ct = execSync("git log -1 --format=%ct", { cwd: root }).toString().trim();
  if (ct) stamp.commit = parts(new Date(Number(ct) * 1000));
} catch {
  // no commits yet / not a repo → leave commit empty
}

// deploy time is meaningful only for an actual deploy.
if (mode === "deploy") stamp.deploy = parts(new Date());

const body =
  "// Generated by scripts/generate-deployment-timestamp.mts — do not edit by hand.\n" +
  `export const lastDeploymentTimestamp: DeploymentStamp = ${JSON.stringify(stamp, null, 2)};\n`;
writeFileSync(outFile, body);
console.log(`wrote src/last-deployment-timestamp.ts (${mode})`);
